import time
import requests


def fetch_urls():
    urls = [
        "https://bitchofrome.com/fandom/transcripts/season1/sinsofthepast.html",
        "https://bitchofrome.com/fandom/transcripts/season1/chariotsofwar.html",
        "https://bitchofrome.com/fandom/transcripts/season1/dreamworker.html",
        "https://bitchofrome.com/fandom/transcripts/season1/cradleofhope.html",
        "https://bitchofrome.com/fandom/transcripts/season1/thepathnottaken.html",
        "https://bitchofrome.com/fandom/transcripts/season1/thereckoning.html",
        "https://bitchofrome.com/fandom/transcripts/season1/thetitans.html",
        "https://bitchofrome.com/fandom/transcripts/season1/prometheus.html",
        "https://bitchofrome.com/fandom/transcripts/season1/deathinchains.html",
        "https://bitchofrome.com/fandom/transcripts/season1/hoovesandharlots.html",
        "https://bitchofrome.com/fandom/transcripts/season1/theblackwolf.html",
        "https://bitchofrome.com/fandom/transcripts/season1/bewaregreeksbearinggifts.html",
        "https://bitchofrome.com/fandom/transcripts/season1/athenscityacademyoftheperformingbards.html",
        "https://bitchofrome.com/fandom/transcripts/season1/afistfulofdinars.html",
        "https://bitchofrome.com/fandom/transcripts/season1/warriorprincess.html",
        "https://bitchofrome.com/fandom/transcripts/season1/mortalbeloved.html",
        "https://bitchofrome.com/fandom/transcripts/season1/theroyalcoupleofthieves.html",
        "https://bitchofrome.com/fandom/transcripts/season1/theprodigal.html",
        "https://bitchofrome.com/fandom/transcripts/season1/altaredstates.html",
        "https://bitchofrome.com/fandom/transcripts/season1/tiesthatbind.html",
        "https://bitchofrome.com/fandom/transcripts/season1/thegreatergood.html",
        "https://bitchofrome.com/fandom/transcripts/season1/callisto.html",
        "https://bitchofrome.com/fandom/transcripts/season1/deathmask.html",
        "https://bitchofrome.com/fandom/transcripts/season1/isthereadoctorinthehouse.html",
        "https://bitchofrome.com/fandom/transcripts/season2/orphanofwar.html",
        "https://bitchofrome.com/fandom/transcripts/season2/remembernothing.html",
        "https://bitchofrome.com/fandom/transcripts/season2/thegiantkiller.html",
        "https://bitchofrome.com/fandom/transcripts/season2/orphanofwar.html",
        "https://bitchofrome.com/fandom/transcripts/season2/remembernothing.html",
        "https://bitchofrome.com/fandom/transcripts/season2/thegiantkiller.html",
        "https://bitchofrome.com/fandom/transcripts/season2/girlsjustwannahavefun.html",
        "https://bitchofrome.com/fandom/transcripts/season2/returnofcallisto.html",
        "https://bitchofrome.com/fandom/transcripts/season2/warriorprincesstramp.html",
        "https://bitchofrome.com/fandom/transcripts/season2/intimatestranger.html",
        "https://bitchofrome.com/fandom/transcripts/season2/tenlittlewarlords.html",
        "https://bitchofrome.com/fandom/transcripts/season2/asolsticecarol.html",
        "https://bitchofrome.com/fandom/transcripts/season2/thexenascrolls.html",
        "https://bitchofrome.com/fandom/transcripts/season2/hereshecomesmissamphipolis.html",
        "https://bitchofrome.com/fandom/transcripts/season2/destiny.html",
        "https://bitchofrome.com/fandom/transcripts/season2/thequest.html",
        "https://bitchofrome.com/fandom/transcripts/season2/anecessaryevil.html",
        "https://bitchofrome.com/fandom/transcripts/season2/adayinthelife.html",
        "https://bitchofrome.com/fandom/transcripts/season2/forhimthebelltolls.html",
        "https://bitchofrome.com/fandom/transcripts/season2/theexecution.html",
        "https://bitchofrome.com/fandom/transcripts/season2/blindfaith.html",
        "https://bitchofrome.com/fandom/transcripts/season2/ulysses.html",
        "https://bitchofrome.com/fandom/transcripts/season2/theprice.html",
        "https://bitchofrome.com/fandom/transcripts/season2/lostmariner.html",
        "https://bitchofrome.com/fandom/transcripts/season2/acomedyoferos.html",
        "https://bitchofrome.com/fandom/transcripts/season3/thefuries.html",
        "https://bitchofrome.com/fandom/transcripts/season3/beentheredonethat.html",
        "https://bitchofrome.com/fandom/transcripts/season3/thedirtyhalfdozen.html",
        "https://bitchofrome.com/fandom/transcripts/season3/thedeliverer.html",
        "https://bitchofrome.com/fandom/transcripts/season3/gabrielleshope.html",
        "https://bitchofrome.com/fandom/transcripts/season3/thedebt.html",
        "https://bitchofrome.com/fandom/transcripts/season3/thedebt2.html",
        "https://bitchofrome.com/fandom/transcripts/season3/thekingofassassins.html",
        "https://bitchofrome.com/fandom/transcripts/season3/warriorpriestesstramp.html",
        "https://bitchofrome.com/fandom/transcripts/season3/thequillismightier.html",
        "https://bitchofrome.com/fandom/transcripts/season3/thebittersuite.html",
        "https://bitchofrome.com/fandom/transcripts/season3/oneagainstanarmy.html",
        "https://bitchofrome.com/fandom/transcripts/season3/forgiven.html",
        "https://bitchofrome.com/fandom/transcripts/season3/kingcon.html",
        "https://bitchofrome.com/fandom/transcripts/season3/wheninrome.html",
        "https://bitchofrome.com/fandom/transcripts/season3/forgetmenot.html",
        "https://bitchofrome.com/fandom/transcripts/season3/finsfemmesgems.html",
        "https://bitchofrome.com/fandom/transcripts/season3/tsunami.html",
        "https://bitchofrome.com/fandom/transcripts/season3/vanishingact.html",
        "https://bitchofrome.com/fandom/transcripts/season3/sacrifice.html",
        "https://bitchofrome.com/fandom/transcripts/season3/sacrifice2.html",
        "https://bitchofrome.com/fandom/transcripts/season4/adventuresinthesintrade.html",
        "https://bitchofrome.com/fandom/transcripts/season4/adventuresinthesintrade2.html",
        "https://bitchofrome.com/fandom/transcripts/season4/afamilyaffair.html",
        "https://bitchofrome.com/fandom/transcripts/season4/insicknessandinhell.html",
        "https://bitchofrome.com/fandom/transcripts/season4/agoodday.html",
        "https://bitchofrome.com/fandom/transcripts/season4/ataleoftwomuses.html",
        "https://bitchofrome.com/fandom/transcripts/season4/lockedupandtieddown.html",
        "https://bitchofrome.com/fandom/transcripts/season4/crusader.html",
        "https://bitchofrome.com/fandom/transcripts/season4/pastimperfect.html",
        "https://bitchofrome.com/fandom/transcripts/season4/thekeytothekingdom.html",
        "https://bitchofrome.com/fandom/transcripts/season4/daughterofpomira.html",
        "https://bitchofrome.com/fandom/transcripts/season4/iftheshoefits.html",
        "https://bitchofrome.com/fandom/transcripts/season4/paradisefound.html",
        "https://bitchofrome.com/fandom/transcripts/season4/devi.html",
        "https://bitchofrome.com/fandom/transcripts/season4/betweenthelines.html",
        "https://bitchofrome.com/fandom/transcripts/season4/theway.html",
        "https://bitchofrome.com/fandom/transcripts/season4/thewayuncut.html",
        "https://bitchofrome.com/fandom/transcripts/season4/theplaysthething.html",
        "https://bitchofrome.com/fandom/transcripts/season4/theconvert.html",
        "https://bitchofrome.com/fandom/transcripts/season4/takesonetoknowone.html",
        "https://bitchofrome.com/fandom/transcripts/season4/endgame.html",
        "https://bitchofrome.com/fandom/transcripts/season4/theidesofmarch.html",
        "https://bitchofrome.com/fandom/transcripts/season4/dejavualloveragain.html",
        "https://bitchofrome.com/fandom/transcripts/season5/fallenangel.html",
        "https://bitchofrome.com/fandom/transcripts/season5/chakram.html",
        "https://bitchofrome.com/fandom/transcripts/season5/succession.html",
        "https://bitchofrome.com/fandom/transcripts/season5/animalattraction.html",
        "https://bitchofrome.com/fandom/transcripts/season5/thembonesthembones.html",
        "https://bitchofrome.com/fandom/transcripts/season5/purity.html",
        "https://bitchofrome.com/fandom/transcripts/season5/backinthebottle.html",
        "https://bitchofrome.com/fandom/transcripts/season5/littleproblems.html",
        "https://bitchofrome.com/fandom/transcripts/season5/seedsoffaith.html",
        "https://bitchofrome.com/fandom/transcripts/season5/lyrelyreheartsonfire.html",
        "https://bitchofrome.com/fandom/transcripts/season5/punchlines.html",
        "https://bitchofrome.com/fandom/transcripts/season5/godfearingchild.html",
        "https://bitchofrome.com/fandom/transcripts/season5/eternalbonds.html",
        "https://bitchofrome.com/fandom/transcripts/season5/amphipolisundersiege.html",
        "https://bitchofrome.com/fandom/transcripts/season5/marriedwithfishsticks.html",
        "https://bitchofrome.com/fandom/transcripts/season5/lifeblood.html",
        "https://bitchofrome.com/fandom/transcripts/season5/kindredspirits.html",
        "https://bitchofrome.com/fandom/transcripts/season5/antonycleopatra.html",
        "https://bitchofrome.com/fandom/transcripts/season5/lookingdeathintheeye.html",
        "https://bitchofrome.com/fandom/transcripts/season5/livia.html",
        "https://bitchofrome.com/fandom/transcripts/season5/eve.html",
        "https://bitchofrome.com/fandom/transcripts/season5/motherhood.html",
        "https://bitchofrome.com/fandom/transcripts/season6/cominghome.html",
        "https://bitchofrome.com/fandom/transcripts/season6/thehauntingofamphipolis.html",
        "https://bitchofrome.com/fandom/transcripts/season6/heartofdarkness.html",
        "https://bitchofrome.com/fandom/transcripts/season6/whosgurkhan.html",
        "https://bitchofrome.com/fandom/transcripts/season6/legacy.html",
        "https://bitchofrome.com/fandom/transcripts/season6/theabyss.html",
        "https://bitchofrome.com/fandom/transcripts/season6/therheingold.html",
        "https://bitchofrome.com/fandom/transcripts/season6/thering.html",
        "https://bitchofrome.com/fandom/transcripts/season6/returnofthevalkyrie.html",
        "https://bitchofrome.com/fandom/transcripts/season6/oldareshadafarm.html",
        "https://bitchofrome.com/fandom/transcripts/season6/dangerousprey.html",
        "https://bitchofrome.com/fandom/transcripts/season6/thegodyouknow.html",
        "https://bitchofrome.com/fandom/transcripts/season6/youarethere.html",
        "https://bitchofrome.com/fandom/transcripts/season6/pathofvengeance.html",
        "https://bitchofrome.com/fandom/transcripts/season6/toheliconandback.html",
        "https://bitchofrome.com/fandom/transcripts/season6/sendintheclones.html",
        "https://bitchofrome.com/fandom/transcripts/season6/lastofthecentaurs.html",
        "https://bitchofrome.com/fandom/transcripts/season6/whenfatescollide.html",
        "https://bitchofrome.com/fandom/transcripts/season6/manyhappyreturns.html",
        "https://bitchofrome.com/fandom/transcripts/season6/soulpossession.html",
        "https://bitchofrome.com/fandom/transcripts/season6/afriendinneed.html",
        "https://bitchofrome.com/fandom/transcripts/season6/afriendinneed2.html"
    ]

    res = [requests.get(addr).status_code for addr in urls]

    print(set(res))


start = time.perf_counter()
fetch_urls()
finish = time.perf_counter()

print(f"Finished in {round(finish - start, 2)} seconds")